# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'npm'


trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - script: echo Hello Stage A!

- stage: B
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: B1
    steps:
      - script: echo Hello Stage B!
      - script: echo $(isMain)
- stage: C
  condition: and(succeeded(),eq(variables.isMain, false))
  jobs:
  - job: C1
   steps:
      - script: echo Hello Stage C!
      - script: echo $(isMain)
- stage: D

